#!/bin/bash
# Push-mode monitoring agent. Sends status updates to the dashboard via POST.
# Required env vars:
#   MONITOR_API_URL - Base URL of the dashboard (e.g. https://stats.cenas-support.com)
#   PUSH_TOKEN      - Per-server push token (generated by the dashboard)
# Optional:
#   SERVICES        - Space-separated list of systemd service names to check
#   DISK_PATHS      - Space-separated list of mountpoints (e.g. "/ /mnt/data")
#   PUSH_INTERVAL   - Seconds between pushes (default 60)

AGENT_VERSION="1.0.0"
AGENT_TYPE="push"
API_URL="${MONITOR_API_URL:?MONITOR_API_URL is required}"
TOKEN="${PUSH_TOKEN:?PUSH_TOKEN is required}"
INTERVAL="${PUSH_INTERVAL:-60}"
SERVICES="${SERVICES:-}"
DISK_PATHS="${DISK_PATHS:-/}"

get_os() {
  if [ -f /etc/os-release ]; then
    . /etc/os-release
    echo "${ID}|${VERSION_ID}"
  else
    echo "unknown|unknown"
  fi
}

get_cpu_usage() {
  awk '{u=$2+$4; t=$2+$4+$5; if (t>0) print int((u/t)*100); else print 0}' /proc/stat 2>/dev/null || echo 0
}

get_mem_info() {
  awk '
    /MemTotal:/ {total=$2}
    /MemAvailable:/ {avail=$2}
    END {
      used = total - avail
      pct = (total>0) ? int((used/total)*100) : 0
      printf "%d|%d|%d|%d", int(total/1024), int(used/1024), int(avail/1024), pct
    }
  ' /proc/meminfo
}

check_service() {
  local name=$1
  if systemctl is-active --quiet "$name" 2>/dev/null; then
    echo "active"
  else
    echo "inactive"
  fi
}

service_version() {
  local name=$1
  local bin="${name%.service}"
  "$bin" --version 2>/dev/null | head -n1 | grep -oE '[0-9]+(\.[0-9]+)+' | head -n1
}

disk_json_for() {
  local path=$1
  local line
  line=$(df -B1 --output=size,used,avail,pcent "$path" 2>/dev/null | tail -n1)
  if [ -z "$line" ]; then return; fi
  local total used avail pcent
  read -r total used avail pcent <<<"$line"
  pcent=${pcent%\%}
  local total_h used_h avail_h
  total_h=$(numfmt --to=iec --suffix=B "$total" 2>/dev/null || echo "$total")
  used_h=$(numfmt --to=iec --suffix=B "$used" 2>/dev/null || echo "$used")
  avail_h=$(numfmt --to=iec --suffix=B "$avail" 2>/dev/null || echo "$avail")
  cat <<EOF
{"name":"disk:$path","type":"disk","status":"active","disk_path":"$path","disk_usage":$pcent,"disk_total":"$total_h","disk_used":"$used_h","disk_available":"$avail_h"}
EOF
}

build_payload() {
  local os_info os_id os_ver
  os_info=$(get_os); os_id="${os_info%|*}"; os_ver="${os_info#*|}"
  local cpu; cpu=$(get_cpu_usage)
  local mem; mem=$(get_mem_info)
  IFS='|' read -r mem_total mem_used mem_avail mem_pct <<<"$mem"

  local services_json="["
  local first=1

  for svc in $SERVICES; do
    local status; status=$(check_service "$svc")
    local version; version=$(service_version "$svc")
    [ $first -eq 0 ] && services_json+=","
    first=0
    services_json+="{\"name\":\"$svc\",\"type\":\"systemd\",\"status\":\"$status\""
    [ -n "$version" ] && services_json+=",\"version\":\"$version\""
    services_json+="}"
  done

  for p in $DISK_PATHS; do
    local d; d=$(disk_json_for "$p")
    if [ -n "$d" ]; then
      [ $first -eq 0 ] && services_json+=","
      first=0
      services_json+="$d"
    fi
  done

  services_json+="]"

  cat <<EOF
{
  "agent_version": "$AGENT_VERSION",
  "agent_type": "$AGENT_TYPE",
  "os": "$os_id",
  "os_version": "$os_ver",
  "cpu_usage": $cpu,
  "memory_total_mb": $mem_total,
  "memory_used_mb": $mem_used,
  "memory_available_mb": $mem_avail,
  "memory_usage": $mem_pct,
  "services": $services_json
}
EOF
}

push_once() {
  local payload; payload=$(build_payload)
  local http_code
  http_code=$(curl -sS -o /tmp/push-agent.resp -w "%{http_code}" \
    -X POST "${API_URL}/api/push" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $TOKEN" \
    --data "$payload")
  echo "[$(date '+%F %T')] push => HTTP $http_code"
  [ "$http_code" = "200" ] || cat /tmp/push-agent.resp
}

if [ "$1" = "--once" ]; then
  push_once
  exit 0
fi

echo "Starting push agent (interval ${INTERVAL}s) to $API_URL"
while true; do
  push_once
  sleep "$INTERVAL"
done
